/**
 * Copyright 2023-present DreamNum Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {
    BooleanNumber,
    LocaleType,
    SheetTypes
} from '@univerjs/core';

/**
 * Default workbook data
 * @type {IWorkbookData} document see https://univer.ai/typedoc/@univerjs/core/interfaces/IWorkbookData
 */
export const DEFAULT_WORKBOOK_DATA = {
    "id": "workbook-01",
    "locale": "zhCn",
    "name": "universheet",
    "sheetOrder": ["sheet-01"],
    "appVersion": "3.0.0-alpha",
    "sheets": {
        "sheet-01": {
            "type": 0,
            "id": "sheet-01",
            "cellData": {
                "0": {
                    "0": {"s": "uAxTlt", "t": 1, "v": "明细表"},
                    "1": {"t": 1, "v": null},
                    "2": {"t": 1, "v": null},
                    "3": {"t": 1, "v": null},
                    "4": {"t": 1, "v": null},
                    "5": {"t": 1, "v": null},
                    "6": {"t": 1, "v": null},
                    "7": {"t": 1, "v": null},
                    "8": {"t": 1, "v": null},
                    "9": {"t": 1, "v": null},
                    "10": {"t": 1, "v": null},
                    "11": {"t": 1, "v": null},
                    "12": {"t": 1, "v": null},
                    "13": {"t": 1, "v": null},
                    "14": {"t": 1, "v": null},
                    "15": {"t": 1, "v": null},
                    "16": {"t": 1, "v": null},
                    "17": {"t": 1, "v": null},
                    "18": {"t": 1, "v": null},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "uAxTlt", "t": 1, "v": "披露表"},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "1": {
                    "0": {"s": "cY35v5", "t": 1, "v": "序号"},
                    "1": {"s": "ibevfN", "t": 1, "v": "项目"},
                    "2": {"s": "ibevfN", "t": 1, "v": "披露口径"},
                    "3": {"s": "ibevfN", "t": 1, "v": "本期账面发生额"},
                    "4": {"s": "ibevfN", "t": 1, "v": "本期送审调整"},
                    "5": {"s": "ibevfN", "t": 1, "v": "本期送审数"},
                    "6": {"s": "hOlMzj", "t": 1, "v": "本期审计调整"},
                    "7": {"s": "fpNWiJ", "t": 1, "v": null},
                    "8": {"s": "ibevfN", "t": 1, "v": "本期审定数"},
                    "9": {"s": "ibevfN", "t": 1, "v": "本期费用占比"},
                    "10": {"s": "ibevfN", "t": 1, "v": "上期账面发生额"},
                    "11": {"s": "ibevfN", "t": 1, "v": "上期送审调整"},
                    "12": {"s": "ibevfN", "t": 1, "v": "上期送审数"},
                    "13": {"s": "hOlMzj", "t": 1, "v": "上期审计调整"},
                    "14": {"s": "fpNWiJ", "t": 1, "v": null},
                    "15": {"s": "ibevfN", "t": 1, "v": "上期审定数"},
                    "16": {"s": "ibevfN", "t": 1, "v": "上期费用占比"},
                    "17": {"s": "ibevfN", "t": 1, "v": "差异额"},
                    "18": {"s": "11rLCi", "t": 1, "v": "差异率"},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": "序号"},
                    "21": {"s": "Vgxq4P", "t": 1, "v": "披露口径"},
                    "22": {"s": "6fdB24", "t": 1, "v": "本年金额"},
                    "23": {"s": "6fdB24", "t": 1, "v": "上年金额"}
                },
                "2": {
                    "0": {"s": "GvoaFq", "t": 1, "v": null},
                    "1": {"s": "GvoaFq", "t": 1, "v": null},
                    "2": {"s": "GvoaFq", "t": 1, "v": null},
                    "3": {"s": "GvoaFq", "t": 1, "v": null},
                    "4": {"s": "GvoaFq", "t": 1, "v": null},
                    "5": {"s": "GvoaFq", "t": 1, "v": null},
                    "6": {"s": "ibevfN", "t": 1, "v": "审计调整"},
                    "7": {"s": "ibevfN", "t": 1, "v": "重分类"},
                    "8": {"s": "GvoaFq", "t": 1, "v": null},
                    "9": {"s": "GvoaFq", "t": 1, "v": null},
                    "10": {"s": "GvoaFq", "t": 1, "v": null},
                    "11": {"s": "GvoaFq", "t": 1, "v": null},
                    "12": {"s": "GvoaFq", "t": 1, "v": null},
                    "13": {"s": "ibevfN", "t": 1, "v": "审计调整"},
                    "14": {"s": "ibevfN", "t": 1, "v": "重分类"},
                    "15": {"s": "GvoaFq", "t": 1, "v": null},
                    "16": {"s": "GvoaFq", "t": 1, "v": null},
                    "17": {"s": "GvoaFq", "t": 1, "v": null},
                    "18": {"s": "GvoaFq", "t": 1, "v": null},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 1},
                    "21": {"s": "kIuZaH", "t": 1, "v": "职工薪酬"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V3,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V3,$P:$P)", "v": null, "t": 2}
                },
                "3": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 1},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用职工薪酬福利费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "职工薪酬"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 49375169.09},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D4+E4", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F4+G4+H4", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I4/$I$23", "v": null, "t": 2, "si": "123123"},
                    "10": {"s": "nzQ2no", "t": 2, "v": 1000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K4+L4", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M4+N4+O4", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P4/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I4-P4", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R4/P4", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 2},
                    "21": {"s": "kIuZaH", "t": 1, "v": "折旧及摊销费用"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V4,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V4,$P:$P)", "v": null, "t": 2}
                },
                "4": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 2},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用折旧费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "折旧及摊销费用"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 18855632.02},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D5+E5", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F5+G5+H5", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I5/$I$23", "v": null, "t": 2, "si": "123123"},
                    "10": {"s": "nzQ2no", "t": 2, "v": 2000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K5+L5", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M5+N5+O5", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P5/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I5-P5", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R5/P5", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 3},
                    "21": {"s": "kIuZaH", "t": 1, "v": "办公费"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V5,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V5,$P:$P)", "v": null, "t": 2}
                },
                "5": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 3},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用摊销费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "折旧及摊销费用"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 2480306.91},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D6+E6", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F6+G6+H6", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I6/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 3000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K6+L6", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M6+N6+O6", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P6/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I6-P6", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R6/P6", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 4},
                    "21": {"s": "kIuZaH", "t": 1, "v": "差旅费"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V6,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V6,$P:$P)", "v": null, "t": 2}
                },
                "6": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 4},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用办公费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "办公费"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 2371231.09},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D7+E7", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F7+G7+H7", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I7/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 4000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K7+L7", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M7+N7+O7", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P7/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I7-P7", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R7/P7", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 5},
                    "21": {"s": "kIuZaH", "t": 1, "v": "其他"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V7,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V7,$P:$P)", "v": null, "t": 2}
                },
                "7": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 5},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用差旅费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "差旅费"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 665341.47},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D8+E8", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F8+G8+H8", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I8/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 5000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K8+L8", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M8+N8+O8", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P8/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I8-P8", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R8/P8", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 6},
                    "21": {"s": "kIuZaH", "t": 1, "v": "咨询及中介服务费用"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V8,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V8,$P:$P)", "v": null, "t": 2}
                },
                "8": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 6},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用租赁费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 79693.51},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D9+E9", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F9+G9+H9", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I9/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 6000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K9+L9", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M9+N9+O9", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P9/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I9-P9", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R9/P9", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": 7},
                    "21": {"s": "kIuZaH", "t": 1, "v": "业务招待费"},
                    "22": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V9,$I:$I)", "v": null, "t": 2},
                    "23": {"s": "aJCtAp", "f": "=SUMIF($C:$C,V9,$P:$P)", "v": null, "t": 2}
                },
                "9": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 7},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用诉讼费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "咨询及中介服务费用"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 506553.98},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D10+E10", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F10+G10+H10", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I10/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 7000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K10+L10", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M10+N10+O10", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P10/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I10-P10", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R10/P10", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"s": "K1u8zD", "t": 1, "v": "合计"},
                    "21": {"s": "jDsALM", "t": 1, "v": null},
                    "22": {"s": "NrueHH", "f": "=SUM(W3:W9)", "v": null, "t": 2},
                    "23": {"s": "NrueHH", "f": "=SUM(X3:X9)", "v": null, "t": 2}
                },
                "10": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 8},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用运输费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "办公费"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 574544.71},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D11+E11", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F11+G11+H11", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I11/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 8000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K11+L11", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M11+N11+O11", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P11/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I11-P11", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R11/P11", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "11": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 9},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用电费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "办公费"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 1391085.46},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D12+E12", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F12+G12+H12", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I12/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 9000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K12+L12", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M12+N12+O12", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P12/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I12-P12", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R12/P12", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "12": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 10},
                    "1": {"s": "M8rSNs", "t": 1, "v": "管理费用职务消费业务招待费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "业务招待费"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 637117.42},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D13+E13", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F13+G13+H13", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I13/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 10000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K13+L13", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M13+N13+O13", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P13/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I13-P13", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R13/P13", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "13": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 11},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用广告宣传费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 1433374.22},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D14+E14", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F14+G14+H14", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I14/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 11000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K14+L14", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M14+N14+O14", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P14/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I14-P14", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R14/P14", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "14": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 12},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用中介机构费用"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 5392382.86},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D15+E15", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F15+G15+H15", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I15/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 12000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K15+L15", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M15+N15+O15", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P15/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I15-P15", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R15/P15", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "15": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 13},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用党团活动经费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 1293516.32},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D16+E16", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F16+G16+H16", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I16/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 13000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K16+L16", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M16+N16+O16", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P16/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I16-P16", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R16/P16", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "16": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 14},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用绿化、环保费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 3528340.6},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D17+E17", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F17+G17+H17", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I17/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 14000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K17+L17", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M17+N17+O17", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P17/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I17-P17", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R17/P17", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "17": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 15},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用职工教育经费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 87423.63},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D18+E18", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F18+G18+H18", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I18/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 15000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K18+L18", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M18+N18+O18", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P18/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I18-P18", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R18/P18", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "18": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 16},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用水土保持补偿费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 482800},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D19+E19", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F19+G19+H19", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I19/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 16000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K19+L19", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M19+N19+O19", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P19/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I19-P19", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R19/P19", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "19": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 17},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用固定资产检修费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 46143506.14},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D20+E20", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F20+G20+H20", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I20/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 17000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K20+L20", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M20+N20+O20", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P20/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I20-P20", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R20/P20", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "20": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 18},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用检验费"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 816203.76},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D21+E21", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F21+G21+H21", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I21/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 18000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K21+L21", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M21+N21+O21", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P21/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I21-P21", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R21/P21", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "21": {
                    "0": {"s": "OCg4lg", "t": 2, "v": 19},
                    "1": {"s": "BBrOIG", "t": 1, "v": "管理费用其他"},
                    "2": {"s": "BBrOIG", "t": 1, "v": "其他"},
                    "3": {"s": "nzQ2no", "t": 2, "v": 517105.23},
                    "4": {"s": "jv97z1", "t": 2, "v": null},
                    "5": {"s": "5LEnRU", "f": "=D22+E22", "v": null, "t": 2},
                    "6": {"s": "E4fYkt", "t": 2, "v": null},
                    "7": {"s": "E4fYkt", "t": 2, "v": null},
                    "8": {"s": "5LEnRU", "f": "=F22+G22+H22", "v": null, "t": 2},
                    "9": {"s": "V3JxEf", "f": "=I22/$I$23", "v": null, "t": 2},
                    "10": {"s": "nzQ2no", "t": 2, "v": 19000000},
                    "11": {"s": "jv97z1", "t": 2, "v": null},
                    "12": {"s": "5LEnRU", "f": "=K22+L22", "v": null, "t": 2},
                    "13": {"s": "E4fYkt", "t": 2, "v": null},
                    "14": {"s": "E4fYkt", "t": 2, "v": null},
                    "15": {"s": "5LEnRU", "f": "=M22+N22+O22", "v": null, "t": 2},
                    "16": {"s": "K4y0K8", "f": "=P22/$P$23", "v": null, "t": 2},
                    "17": {"s": "BKKxXX", "f": "=I22-P22", "v": null, "t": 2},
                    "18": {"s": "3PArBc", "f": "=R22/P22", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                },
                "22": {
                    "0": {"s": "zkUirc", "t": 1, "v": "合计"},
                    "1": {"s": "3sEUN5", "t": 1, "v": null},
                    "2": {"s": "w4PNIB", "t": 1, "v": null},
                    "3": {"s": "gDMMps", "f": "=SUM(D4:D22)", "v": null, "t": 2},
                    "4": {"s": "gDMMps", "f": "=SUM(E4:E22)", "v": null, "t": 2},
                    "5": {"s": "gDMMps", "f": "=SUM(F4:F22)", "v": null, "t": 2},
                    "6": {"s": "gDMMps", "f": "=SUM(G4:G22)", "v": null, "t": 2},
                    "7": {"s": "gDMMps", "f": "=SUM(H4:H22)", "v": null, "t": 2},
                    "8": {"s": "gDMMps", "f": "=SUM(I4:I22)", "v": null, "t": 2},
                    "9": {"s": "4DVw9N", "f": "=SUM(J4:J22)", "v": null, "t": 2},
                    "10": {"s": "gDMMps", "f": "=SUM(K4:K22)", "v": null, "t": 2},
                    "11": {"s": "gDMMps", "f": "=SUM(L4:L22)", "v": null, "t": 2},
                    "12": {"s": "gDMMps", "f": "=SUM(M4:M22)", "v": null, "t": 2},
                    "13": {"s": "gDMMps", "f": "=SUM(N4:N22)", "v": null, "t": 2},
                    "14": {"s": "gDMMps", "f": "=SUM(O4:O22)", "v": null, "t": 2},
                    "15": {"s": "gDMMps", "f": "=SUM(P4:P22)", "v": null, "t": 2},
                    "16": {"s": "wqmkJe", "f": "=SUM(Q4:Q22)", "v": null, "t": 2},
                    "17": {"s": "gDMMps", "f": "=I23-P23", "v": null, "t": 2},
                    "18": {"s": "4DVw9N", "f": "=R23/P23", "v": null, "t": 2},
                    "19": {"t": 1, "v": null},
                    "20": {"t": 1, "v": null},
                    "21": {"t": 1, "v": null},
                    "22": {"t": 1, "v": null},
                    "23": {"t": 1, "v": null}
                }
            },
            "name": "管理费用",
            "hidden": 0,
            "rowCount": 23,
            "columnCount": 24,
            "zoomRatio": 1,
            "scrollTop": 0,
            "scrollLeft": 0,
            "defaultColumnWidth": 93,
            "defaultRowHeight": 27,
            "status": 1,
            "showGridlines": 1,
            "hideRow": [],
            "hideColumn": [],
            "rowHeader": {"width": 46, "hidden": 0},
            "columnHeader": {"height": 20, "hidden": 0},
            "selections": [],
            "rightToLeft": 0,
            "pluginMeta": {},
            "mergeData": [{
                "startRow": 1,
                "startColumn": 6,
                "endRow": 1,
                "endColumn": 7,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 2, "endRow": 2, "endColumn": 2, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 5,
                "endRow": 2,
                "endColumn": 5,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 9, "endRow": 2, "endColumn": 9, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 13,
                "endRow": 1,
                "endColumn": 14,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 10, "endRow": 2, "endColumn": 10, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 12,
                "endRow": 2,
                "endColumn": 12,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 1, "endRow": 2, "endColumn": 1, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 0,
                "endRow": 2,
                "endColumn": 0,
                "rangeType": 0
            }, {"startRow": 22, "startColumn": 0, "endRow": 22, "endColumn": 1, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 3,
                "endRow": 2,
                "endColumn": 3,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 16, "endRow": 2, "endColumn": 16, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 15,
                "endRow": 2,
                "endColumn": 15,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 4, "endRow": 2, "endColumn": 4, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 18,
                "endRow": 2,
                "endColumn": 18,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 8, "endRow": 2, "endColumn": 8, "rangeType": 0}, {
                "startRow": 1,
                "startColumn": 17,
                "endRow": 2,
                "endColumn": 17,
                "rangeType": 0
            }, {"startRow": 1, "startColumn": 11, "endRow": 2, "endColumn": 11, "rangeType": 0}],
            "rowData": {
                "0": {"hd": 0, "h": 29.326},
                "1": {"hd": 0, "h": 29.326},
                "2": {"hd": 0, "h": 22.661},
                "3": {"hd": 0, "h": 45.322},
                "4": {"hd": 0, "h": 22.661},
                "5": {"hd": 0, "h": 22.661},
                "6": {"hd": 0, "h": 22.661},
                "7": {"hd": 0, "h": 45.322},
                "8": {"hd": 0, "h": 22.661},
                "9": {"hd": 0, "h": 29.326},
                "10": {"hd": 0, "h": 29.326},
                "11": {"hd": 0, "h": 29.326},
                "12": {"hd": 0, "h": 41.323},
                "13": {"hd": 0, "h": 29.326},
                "14": {"hd": 0, "h": 29.326},
                "15": {"hd": 0, "h": 29.326},
                "16": {"hd": 0, "h": 29.326},
                "17": {"hd": 0, "h": 29.326},
                "18": {"hd": 0, "h": 29.326},
                "19": {"hd": 0, "h": 29.326},
                "20": {"hd": 0, "h": 29.326},
                "21": {"hd": 0, "h": 29.326},
                "22": {"hd": 0, "h": 29.326}
            },
            "columnData": {
                "0": {"w": 55.375, "hd": 0},
                "1": {"w": 159.4375, "hd": 0},
                "2": {"w": 96, "hd": 0},
                "3": {"w": 102.5, "hd": 0},
                "4": {"w": 96, "hd": 0},
                "5": {"w": 98.3124999999997, "hd": 0},
                "6": {"w": 96, "hd": 0},
                "7": {"w": 96, "hd": 0},
                "8": {"w": 94.5625000000003, "hd": 0},
                "9": {"w": 80.5625000000003, "hd": 0},
                "10": {"w": 112.3125, "hd": 0},
                "11": {"w": 96, "hd": 0},
                "12": {"w": 88.0624999999998, "hd": 0},
                "13": {"w": 96, "hd": 0},
                "14": {"w": 96, "hd": 0},
                "15": {"w": 97.6874999999998, "hd": 0},
                "16": {"w": 96, "hd": 0},
                "17": {"w": 102.5, "hd": 0},
                "18": {"w": 96, "hd": 0},
                "19": {"w": 96, "hd": 0},
                "20": {"w": 96, "hd": 0},
                "21": {"w": 98.3124999999997, "hd": 0},
                "22": {"w": 109.1875, "hd": 0},
                "23": {"w": 105, "hd": 0}
            }
        },
    },
    "styles": {
        "uAxTlt": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(255,0,0)",
            "bg": {"rgb": "rgb(255,255,0)"},
            "n": {"pattern": "General"}
        },
        "cY35v5": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "@"}
        },
        "ibevfN": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "hOlMzj": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "fpNWiJ": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {"b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}, "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}},
            "n": {"pattern": "General"}
        },
        "11rLCi": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0.00%"}
        },
        "K1u8zD": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "Vgxq4P": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(191,191,191)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "#,##0.00_ "}
        },
        "6fdB24": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(191,191,191)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "#,##0.00_ "}
        },
        "GvoaFq": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "kIuZaH": {
            "ht": 1,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "#,##0.00;\\-#,##0.00;;@"}
        },
        "aJCtAp": {
            "ht": 3,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(204,255,204)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "OCg4lg": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "@"}
        },
        "BBrOIG": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "nzQ2no": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "jv97z1": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "5LEnRU": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(192,229,244)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "E4fYkt": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 1,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(255,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "V3JxEf": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(192,229,244)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0.00%"}
        },
        "K4y0K8": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(192,229,244)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0%"}
        },
        "BKKxXX": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 9,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(192,229,244)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "3PArBc": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 9,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(192,229,244)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0.00%"}
        },
        "jDsALM": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "NrueHH": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 9,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "M8rSNs": {
            "ht": 1,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "宋体-简",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(191,191,191)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "#,##0.00_ "}
        },
        "zkUirc": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(70,178,225)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "3sEUN5": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "w4PNIB": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(70,178,225)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "gDMMps": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(70,178,225)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "4DVw9N": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(70,178,225)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0.00%"}
        },
        "wqmkJe": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Times New Roman",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(70,178,225)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "0%"}
        },
        "diBXkm": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,0)"},
            "n": {"pattern": "General"}
        },
        "vChpkq": {
            "ht": 2,
            "vt": 2,
            "bl": 1,
            "it": 0,
            "ff": "宋体",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "q8G7rd": {
            "ht": 2,
            "vt": 2,
            "bl": 1,
            "it": 0,
            "ff": "等线",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "U7uEeR": {
            "ht": 2,
            "vt": 2,
            "bl": 1,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "cYgvlV": {
            "ht": 0,
            "vt": 0,
            "bl": 1,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7}
            },
            "n": {"pattern": "General"}
        },
        "dz9981": {
            "ht": 2,
            "vt": 2,
            "bl": 1,
            "it": 0,
            "ff": "微软雅黑",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7}
            },
            "n": {"pattern": "General"}
        },
        "scgm7m": {
            "ht": 2,
            "vt": 2,
            "bl": 1,
            "it": 0,
            "ff": "微软雅黑",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7}
            },
            "n": {"pattern": "General"}
        },
        "cOjbG3": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "Y1Y1w0": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "OonGc3": {
            "ht": 1,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "B5gPYx": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "c5YeRM": {
            "ht": 2,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "V15WAR": {
            "ht": 0,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "General"}
        },
        "KPC9O4": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "4ezPDO": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "zBqENJ": {
            "ht": 1,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "General"}
        },
        "6woc7e": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "微软雅黑",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(242,242,242)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "CEolmg": {
            "ht": 2,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "微软雅黑",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(242,242,242)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "General"}
        },
        "LSxG5Y": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 10,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(242,242,242)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 1}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "peMjFM": {
            "ht": 0,
            "vt": 2,
            "bl": 0,
            "it": 0,
            "ff": "等线",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "C6vM8Y": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "HtIJbm": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "r": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        },
        "5GAv4J": {
            "ht": 3,
            "vt": 0,
            "bl": 0,
            "it": 0,
            "ff": "Arial",
            "fs": 11,
            "cl": "rgb(0,0,0)",
            "bg": {"rgb": "rgb(255,255,255)"},
            "bd": {
                "b": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 7},
                "l": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2},
                "t": {"cl": {"rgb": "rgb(102,102,102)"}, "s": 2}
            },
            "n": {"pattern": "_ * #,##0.00_ ;_ * \\-#,##0.00_ ;_ * \"-\"??_ ;_ @_ "}
        }
    }
}
